export const REQUEST_COURSES = 'REQUEST_COURSES';
export const REQUEST_SAVE_COURSES = 'REQUEST_SAVE_COURSES';
export const REQUEST_DELETE_COURSES = 'REQUEST_DELETE_COURSES';
export const SUCCESS_COURSES = 'SUCCESS_COURSES';
export const ERROR_COURSES = 'ERROR_COURSES';
export const ERROR_SAVE_COURSES = 'ERROR_SAVE_COURSES';
export const ERROR_DELETE_COURSES = 'ERROR_DELETE_COURSES';
export const SUCCESS_SAVE_COURSES = 'SUCCESS_SAVE_COURSES';
export const SUCCESS_EDIT_COURSES = 'SUCCESS_EDIT_COURSES';
export const SUCCESS_DELETE_COURSES = 'SUCCESS_DELETE_COURSES';

export const REQUEST_AUTHORS = 'REQUEST_AUTHORS';
export const SUCCESS_AUTHORS = 'SUCCESS_AUTHORS';
export const ERROR_AUTHORS = 'ERROR_AUTHORS';
